# Generated by Django 3.2.7 on 2021-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='handicap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
